<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Tomás Urzúa">
<title>La alfabetización digital en escolares del mundo actual</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="Entrega final multinivel_files/libs/clipboard/clipboard.min.js"></script>
<script src="Entrega final multinivel_files/libs/quarto-html/quarto.js"></script>
<script src="Entrega final multinivel_files/libs/quarto-html/popper.min.js"></script>
<script src="Entrega final multinivel_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Entrega final multinivel_files/libs/quarto-html/anchor.min.js"></script>
<link href="Entrega final multinivel_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Entrega final multinivel_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Entrega final multinivel_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Entrega final multinivel_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Entrega final multinivel_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script src="Entrega%20final%20multinivel_files/libs/kePrint-0.0.1/kePrint.js"></script><link href="Entrega%20final%20multinivel_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link href="Entrega%20final%20multinivel_files/libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet">
<script src="Entrega%20final%20multinivel_files/libs/bsTable-3.3.7/bootstrapTable.js"></script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body>

<header id="title-block-header" class="quarto-title-block default page-columns page-full"><div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">La alfabetización digital en escolares del mundo actual</h1>
            <p class="subtitle lead">Un estudio de sus determinantes mediante modelamiento multinivel</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Autor/a</div>
      <div class="quarto-title-meta-contents">
               <p>Tomás Urzúa </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Fecha de publicación</div>
      <div class="quarto-title-meta-contents">
        <p class="date">30 de junio de 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="1"><h2 id="toc-title">Contenidos</h2>
   
  <ul class="collapse">
<li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract"><span class="header-section-number">1</span> Abstract</a></li>
  <li><a href="#introducci%C3%B3n" id="toc-introducción" class="nav-link" data-scroll-target="#introducci%C3%B3n"><span class="header-section-number">2</span> Introducción</a></li>
  <li>
<a href="#factores-asociados" id="toc-factores-asociados" class="nav-link" data-scroll-target="#factores-asociados"><span class="header-section-number">3</span> Factores asociados</a>
  <ul class="collapse">
<li><a href="#nivel-individual" id="toc-nivel-individual" class="nav-link" data-scroll-target="#nivel-individual"><span class="header-section-number">3.1</span> Nivel individual</a></li>
  <li><a href="#nivel-pa%C3%ADs" id="toc-nivel-país" class="nav-link" data-scroll-target="#nivel-pa%C3%ADs"><span class="header-section-number">3.2</span> Nivel país</a></li>
  <li><a href="#interacci%C3%B3n-entre-niveles" id="toc-interacción-entre-niveles" class="nav-link" data-scroll-target="#interacci%C3%B3n-entre-niveles"><span class="header-section-number">3.3</span> Interacción entre niveles</a></li>
  <li><a href="#objetivo-e-hip%C3%B3tesis" id="toc-objetivo-e-hipótesis" class="nav-link" data-scroll-target="#objetivo-e-hip%C3%B3tesis"><span class="header-section-number">3.4</span> Objetivo e hipótesis</a></li>
  </ul>
</li>
  <li>
<a href="#datos-variables-y-m%C3%A9todos" id="toc-datos-variables-y-métodos" class="nav-link" data-scroll-target="#datos-variables-y-m%C3%A9todos"><span class="header-section-number">4</span> Datos, variables y métodos</a>
  <ul class="collapse">
<li><a href="#variables" id="toc-variables" class="nav-link" data-scroll-target="#variables"><span class="header-section-number">4.1</span> Variables</a></li>
  <li><a href="#m%C3%A9todos" id="toc-métodos" class="nav-link" data-scroll-target="#m%C3%A9todos"><span class="header-section-number">4.2</span> Métodos</a></li>
  </ul>
</li>
  <li>
<a href="#resultados" id="toc-resultados" class="nav-link" data-scroll-target="#resultados"><span class="header-section-number">5</span> Resultados</a>
  <ul class="collapse">
<li><a href="#descriptivos" id="toc-descriptivos" class="nav-link" data-scroll-target="#descriptivos"><span class="header-section-number">5.1</span> Descriptivos</a></li>
  <li><a href="#modelos" id="toc-modelos" class="nav-link" data-scroll-target="#modelos"><span class="header-section-number">5.2</span> Modelos</a></li>
  <li><a href="#ajuste" id="toc-ajuste" class="nav-link" data-scroll-target="#ajuste"><span class="header-section-number">5.3</span> Ajuste</a></li>
  <li><a href="#casos-influyentes" id="toc-casos-influyentes" class="nav-link" data-scroll-target="#casos-influyentes"><span class="header-section-number">5.4</span> Casos influyentes</a></li>
  </ul>
</li>
  <li><a href="#discusi%C3%B3n" id="toc-discusión" class="nav-link" data-scroll-target="#discusi%C3%B3n"><span class="header-section-number">6</span> Discusión</a></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones"><span class="header-section-number">7</span> Conclusiones</a></li>
  <li><a href="#anexo" id="toc-anexo" class="nav-link" data-scroll-target="#anexo"><span class="header-section-number">8</span> Anexo</a></li>
  </ul></nav>
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content"><section id="abstract" class="level1" data-number="1"><h1 data-number="1">
<span class="header-section-number">1</span> Abstract</h1>
<p>La creciente digitalización ha suscitado nuevas desigualdades en torno a la disponibilidad y el uso y conocimientos de las tecnologías digitales. Para estrechar estas brechas, la alfabetización digital se presenta no sólo como una solución, sino como una competencia fundamental para la vida en la sociedad actual. Los estudiantes conviven en entornos digitales cotidianamente, pero no todos poseen la misma masterización en habilidades digitales. Al respecto, las condiciones del país en que se encuentran los jóvenes juegan un rol clave, en donde estas condiciones estructurales pueden determinar la alfabetización digital. Esta investigación tiene como objetivo explorar las determinantes a nivel individual y a nivel país que inciden en la alfabetización digital de los estudiantes. Se utiliza la base de datos ICILS 2023 (N = 135615 en 35 países) aplicando modelamiento multinivel. Los resultados indican a nivel individual la relevancia del sexo y nivel socioeconómico del estudiante para determinar la alfabetización digital, mientras que en el nivel dos la riqueza del país es más importante que un gobierno digitalizado en la alfabetización digital de sus estudiantes.</p>
</section><section id="introducción" class="level1" data-number="2"><h1 data-number="2">
<span class="header-section-number">2</span> Introducción</h1>
<p>Durante las últimas décadas las nuevas tecnologías se han expandido a un ritmo exponencial y vertiginoso, lo cual ha suscitado diversas interrogantes en torno a su presencia en la sociedad y, sobre todo, a los usos que se les dan a ellas. Efectivamente, en la actualidad la mayoría de las interacciones sociales se ven mediadas por la digitalidad, la cual ha logrado inscribirse en la cultura popular de las nuevas generaciones, formando parte constitutiva de sus trayectorias <span class="citation" data-cites="buckingham_mas_2008">(<a href="#ref-buckingham_mas_2008" role="doc-biblioref">Buckingham 2008</a>)</span>. En este contexto, la proliferación de las Tecnologías de Información y Comunicación juega un rol sumamente relevante para la sociedad en tanto han fomentado el mejoramiento en la calidad de vida humana, aportando en diversos campos como la salud, la educación, la banca, el transporte y la gobernanza digital <span class="citation" data-cites="reddy_student_2020 nand_metaheuristic_2019 sharma_smart_2018 reddy_tablet_2017 pojani_sustainable_2015 sharma_use_2015">(<a href="#ref-reddy_student_2020" role="doc-biblioref">Pritika Reddy, Sharma, y Chandra 2020</a>; <a href="#ref-nand_metaheuristic_2019" role="doc-biblioref">Nand y Sharma 2019</a>; <a href="#ref-sharma_smart_2018" role="doc-biblioref">Bibhya Nand Sharma et&nbsp;al. 2018</a>; <a href="#ref-reddy_tablet_2017" role="doc-biblioref">P. Reddy, Sharma, y Chandra 2017</a>; <a href="#ref-pojani_sustainable_2015" role="doc-biblioref">Pojani y Stead 2015</a>; <a href="#ref-sharma_use_2015" role="doc-biblioref">Bibhya N. Sharma et&nbsp;al. 2015</a>)</span>.</p>
<p>Estas nuevas tecnologías han irrumpido con fuerza en los procesos de enseñanza y aprendizaje de los establecimientos educacionales, viéndose la educación como el campo para abordar los desafíos que imponen estas transformaciones <span class="citation" data-cites="sunkel_aprender_2011">(<a href="#ref-sunkel_aprender_2011" role="doc-biblioref">Sunkel, Trucco, y Möller 2011</a>)</span>. La implementación de las TIC en la educación ha generado expectativas al punto de considerarse como un catalizador para la reducción de las desigualdades <span class="citation" data-cites="claro_impacto_2010">(<a href="#ref-claro_impacto_2010" role="doc-biblioref">Claro 2010</a>)</span>. Aun así, es sumamente importante que, además de que exista equidad respecto a la infraestructura tecnológica existente en las escuelas, también hay que preocuparse de las habilidades que poseen las personas para desenvolverse con las TIC.</p>
<p>El desarrollo de las tecnologías digitales también ha generado la emergencia de otras brechas. Este fenómeno ha tomado el nombre de brecha digital, cuyo significado corresponde a la distancia que se produce entre los individuos y sociedades que pueden acceder y participar de la era de la información y los que no los tienen <span class="citation" data-cites="dijk_digital_2020">(<a href="#ref-dijk_digital_2020" role="doc-biblioref">Dijk 2020</a>)</span>. Uno de los problemas más perjudiciales de la brecha digital es que se piensa que su padecimiento implica la agudización de otras brechas, tales como la económica y la social <span class="citation" data-cites="camacho_brecha_2005">(<a href="#ref-camacho_brecha_2005" role="doc-biblioref">Camacho 2005</a>)</span>. En la misma línea, se ha planteado el surgimiento de una segunda brecha digital, asociada a las habilidades necesarias para relacionarse y operar de manera adecuada las TIC <span class="citation" data-cites="claro_impacto_2010">(<a href="#ref-claro_impacto_2010" role="doc-biblioref">Claro 2010</a>)</span>.</p>
<p>En este contexto, la alfabetización digital surge como una alternativa que posibilita hacer frente a las brechas digitales a través del desarrollo de habilidades necesarias para ser usuario de la información digital, tales como la aptitud para identificar la calidad de un contenido y/o la adaptabilidad a diversos contextos en el uso de TIC <span class="citation" data-cites="castells_sociedad_2006 garcia-avila_alfabetizacion_2017">(<a href="#ref-castells_sociedad_2006" role="doc-biblioref">Castells 2006</a>; <a href="#ref-garcia-avila_alfabetizacion_2017" role="doc-biblioref">García-Ávila 2017</a>)</span>. A pesar de ser un concepto cada vez más relevante, no existe una definición universal de la alfabetización digital, ni tampoco una pauta general de cómo medirla. Sobre aquello, el estudio International Computer and Information Literacy Study operacionaliza el concepto en alfabetización computacional y manejo de la información de tal manera que pueda ser medido, entendiéndolo como la capacidad individual para utilizar computadores con fines de investigación, creación y comunicación, con tal de participar de manera eficaz en el hogar, la escuela, el lugar de trabajo y la sociedad <span class="citation" data-cites="fraillon_icils_2013">(<a href="#ref-fraillon_icils_2013" role="doc-biblioref">Fraillon et&nbsp;al. 2013</a>)</span>.</p>
<p>Es importante precisar que, aunque la alfabetización digital pueda concebirse como una opción para reducir la exclusión digital, debe comprenderse más allá de su carácter resolutivo y considerarse como una de las piedras angulares para el desarrollo humano actual en tanto dota de una capacidad agencial a los individuos al permitirles desplegarse activamente en los nuevos entornos que involucran la digitalidad, lo que consecuentemente los lleva a integrarse a la sociedad apropiadamente y no quedar marginados de la ciudadanía <span class="citation" data-cites="silvera_alfabetizacion_2005 barroso_investigacion_2011 cabero_tendencias_2016">(<a href="#ref-silvera_alfabetizacion_2005" role="doc-biblioref">Silvera 2005</a>; <a href="#ref-barroso_investigacion_2011" role="doc-biblioref">Barroso y Cabero 2011</a>; <a href="#ref-cabero_tendencias_2016" role="doc-biblioref">Cabero 2016</a>)</span>.</p>
<p>Las brechas digitales poseen este carácter individual, en donde ciertos grupos gozan de los beneficios que proporcionan estas tecnologías, mientras otros son relegados a quedar fuera del mundo digital, pero esta lógica también observarse entre países, pues existen países que se encuentran mejor posicionados frente al malestar digital que otros <span class="citation" data-cites="silvera_alfabetizacion_2005">(<a href="#ref-silvera_alfabetizacion_2005" role="doc-biblioref">Silvera 2005</a>)</span>. De hecho, existen diferencias sustantivas respecto al desarrollo e implementación de las TIC entre regiones. Los países desarrollados han logrado superar en cierta medida la primera brecha digital, mientras en Latinoamérica aún no se ha encontrado alguna resolución respecto a los problemas de acceso a las TIC <span class="citation" data-cites="claro_impacto_2010">(<a href="#ref-claro_impacto_2010" role="doc-biblioref">Claro 2010</a>)</span>.</p>
<p>Generalmente, los países desarrollados tienden a tener mejores resultados en estudios comparativos internacionales que países subdesarrollados <span class="citation" data-cites="oecd_pisa_2023 iea_pirls_2021">(<a href="#ref-oecd_pisa_2023" role="doc-biblioref">OECD 2023</a>; <a href="#ref-iea_pirls_2021" role="doc-biblioref">IEA 2021</a>)</span>. Estas diferencias pueden explicarse por factores culturales, económicas y/o educativos particulares de cada país, lo que puede dar lugar a experiencias diferentes de los estudiantes dependiendo de su pertenencia. Señalar estas diferencias entre países constituye un paso importante para la evaluación de los sistemas educativos <span class="citation" data-cites="punter_gender_2017">(<a href="#ref-punter_gender_2017" role="doc-biblioref">Punter, Meelissen, y Glas 2017</a>)</span>.</p>
<p>Existen estudios que han intentado aplicar un enfoque comparativo para dar cuenta de cómo varía la relevancia de los predictores dependiendo el país. En este marco, está el estudio de <span class="citation" data-cites="gerick_schoollevel_2017">Gerick, Eickelmann, y Bos (<a href="#ref-gerick_schoollevel_2017" role="doc-biblioref">2017</a>)</span>, cuyo propósito fue evidenciar cuáles son los factores a nivel escuela que apoyan u obstaculizan el uso de TIC por parte de profesores y estudiantes, comparando entre Australia, Alemania, Noruega y República Checa; sus resultados indican que sólo en Alemania la alfabetización digital no implica necesariamente disponibilidad de infraestructura tecnológica. Por su parte, <span class="citation" data-cites="aydin_multilevel_2022">Aydin (<a href="#ref-aydin_multilevel_2022" role="doc-biblioref">2022</a>)</span> se centró en indagar en los determinantes de la alfabetización digital en alumnos, realizando un estudio que examinó las características de los profesores y los estudiantes mediante un análisis comparativo entre Finlandia y Corea.</p>
<p>Considerando la importancia de la pertenencia a un país respecto al desempeño académico, este trabajo pretende explorar en los factores que inciden en la alfabetización digital a través de un análisis comparado entre países, con tal de dilucidar cómo se comportan estos predictores dependiendo la región. Tomando en cuenta esto, se propone la siguiente pregunta de investigación: <strong>¿De qué manera se relacionan los factores individuales y contextuales a nivel país en el logro de alfabetización digital de los estudiantes?</strong></p>
</section><section id="factores-asociados" class="level1" data-number="3"><h1 data-number="3">
<span class="header-section-number">3</span> Factores asociados</h1>
<section id="nivel-individual" class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="nivel-individual">
<span class="header-section-number">3.1</span> Nivel individual</h2>
<p>El género es factor fundamental al momento de estudiar la alfabetización digital, pues mediante dinámicas de estigmatización las mujeres han sido opacadas en el campo tecnológico, viéndose relegadas a ocupar una posición inferior en cuanto al dominio digital, pero la manera en que se comprenden estos resultados ha cambiado en el tiempo <span class="citation" data-cites="fairlie_boys_2016">(<a href="#ref-fairlie_boys_2016" role="doc-biblioref">Fairlie 2016</a>)</span>. Mientras que estudios anteriores solían indicar que los niños tenían ventaja en cuanto a habilidades digitales, investigaciones más recientes revelan que las brechas de género se están reduciendo o incluso invirtiendo, y que en algunos contextos las niñas superan a los niños en las evaluaciones de alfabetización digital <span class="citation" data-cites="caponera_exploring_2025 heldt_relationship_2020">(<a href="#ref-caponera_exploring_2025" role="doc-biblioref">Caponera, Annunziata, y Palmerio 2025</a>; <a href="#ref-heldt_relationship_2020" role="doc-biblioref">Heldt et&nbsp;al. 2020</a>)</span>.</p>
<p>El nivel socioeconómico ha sido históricamente comprendido como un determinante en el logro de resultados de estudiantes <span class="citation" data-cites="cervini_desigualdades_2002 chaparrocasolopez_familia_2016">(<a href="#ref-cervini_desigualdades_2002" role="doc-biblioref">Cervini 2002</a>; <a href="#ref-chaparrocasolopez_familia_2016" role="doc-biblioref">Chaparro Caso López, González Barbera, y Caso Niebla 2016</a>)</span>. Hay posturas que defienden la educación como el principal motor de generación de oportunidades y movilidad social <span class="citation" data-cites="collins_sociedad_1989">(<a href="#ref-collins_sociedad_1989" role="doc-biblioref">Collins 1989</a>)</span>, pero también la contraparte que señala las escuelas como meros sistemas de reproducción social que perpetúan las desigualdades de base de los jóvenes <span class="citation" data-cites="bourdieu_herederos_2009">(<a href="#ref-bourdieu_herederos_2009" role="doc-biblioref">Bourdieu y Passeron 2009</a>)</span>. El contexto digital no es la excepción, pues investigaciones empíricas han demostrado la diferencia en puntajes de alfabetización digital cuando el contexto socioeconómico del estudiante es tomado en cuenta, en donde aquellos con mejores condiciones tienen desempeños más destacados que sus pares <span class="citation" data-cites="heldt_relationship_2020 aesaert_information_2018">(<a href="#ref-heldt_relationship_2020" role="doc-biblioref">Heldt et&nbsp;al. 2020</a>; <a href="#ref-aesaert_information_2018" role="doc-biblioref">Aesaert y van Braak 2018</a>)</span>.</p>
<p>La autoeficacia digital es otro concepto ampliamente reconocido como un indicador clave de la alfabetización digital de los estudiantes, entendido como la autopercepción del individuo sobre su propio desempeño en alguna actividad específica <span class="citation" data-cites="bandura_selfefficacy_1982a">(<a href="#ref-bandura_selfefficacy_1982a" role="doc-biblioref">Bandura 1982</a>)</span>. Los estudiantes que creen en su capacidad para utilizar eficazmente las tecnologías digitales son más propensos a utilizar herramientas digitales, explorar nuevas aplicaciones y persistir en la superación de retos <span class="citation" data-cites="tsai_junior_2010">(<a href="#ref-tsai_junior_2010" role="doc-biblioref">Tsai y Tsai 2010</a>)</span>. Una mayor autoeficacia digital se asocia con una mayor confianza en la navegación por entornos en línea, lo que se traduce en una mejora de las habilidades digitales y los resultados del aprendizaje <span class="citation" data-cites="hatlevik_digital_2015">(<a href="#ref-hatlevik_digital_2015" role="doc-biblioref">Hatlevik, Gumundsdóttir, y Loi 2015</a>)</span>. Por lo tanto, la autoeficacia digital se presenta como un mecanismo importante a través del cual los entornos educativos pueden ayudar a salvar las brechas de habilidades digitales.</p>
</section><section id="nivel-país" class="level2" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="nivel-país">
<span class="header-section-number">3.2</span> Nivel país</h2>
<p>Las diferencias entre países en materia de alfabetización digital están determinadas por una serie de factores a nivel nacional, especialmente por indicadores socioeconómicos tales como el producto interno bruto (PIB) per cápita. Los países con PIB más elevado tienden a ofrecer un mejor acceso a los recursos digitales, tanto en el hogar como en las escuelas, lo que facilita la adquisición de competencias digitales entre los estudiantes <span class="citation" data-cites="gerick_schoollevel_2017">(<a href="#ref-gerick_schoollevel_2017" role="doc-biblioref">Gerick, Eickelmann, y Bos 2017</a>)</span>. Además, la prosperidad económica permite una mayor inversión en tecnología educativa, formación del profesorado y entornos de aprendizaje digital, lo que contribuye a obtener puntuaciones medias más altas en alfabetización digital <span class="citation" data-cites="scherer_gender_2023">(<a href="#ref-scherer_gender_2023" role="doc-biblioref">Scherer et&nbsp;al. 2023</a>)</span>.</p>
<p>El estado y los gobiernos han sufrido una reconfiguración de su organización gracias a los procesos de digitalización. Los estados de bienestar han debido reinventar su funcionamiento a propósito de la emergencia de las plataformas online, lo que ha ayudado a promover nuevas oportunidades laborales, así como se han ampliado las modalidades para realizar trámites <span class="citation" data-cites="busemeyer_digitalization_2022">(<a href="#ref-busemeyer_digitalization_2022" role="doc-biblioref">Busemeyer et&nbsp;al. 2022</a>)</span>. Al respecto, los países con una infraestructura digital avanzada ofrecen oportunidades más equitativas para que los estudiantes desarrollen competencias digitales, mientras que aquellos con una infraestructura limitada pueden agravar las desigualdades existentes <span class="citation" data-cites="fraillon_preparing_2020">(<a href="#ref-fraillon_preparing_2020" role="doc-biblioref">Fraillon et&nbsp;al. 2020</a>)</span>.</p>
</section><section id="interacción-entre-niveles" class="level2" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="interacción-entre-niveles">
<span class="header-section-number">3.3</span> Interacción entre niveles</h2>
<p>Las condiciones socioeconómicas de un país pueden moderar la relación entre el puntaje de alfabetización digital y el nivel socioeconómico de los estudiantes. Los países más ricos, sobre todo en Europa, suelen ser también más igualitarios en términos económicos y, al mismo tiempo, tener puntajes de alfabetización digital sobre el promedio <span class="citation" data-cites="fraillon_icils_2024">(<a href="#ref-fraillon_icils_2024" role="doc-biblioref">Fraillon 2024</a>)</span>. En esta lógica, se esperaría que en los países económicamente desventajados, las disparidades en el puntaje de alfabetización digital sean exacerbadas por el nivel socioeconómico de los estudiantes.</p>
</section><section id="objetivo-e-hipótesis" class="level2" data-number="3.4"><h2 data-number="3.4" class="anchored" data-anchor-id="objetivo-e-hipótesis">
<span class="header-section-number">3.4</span> Objetivo e hipótesis</h2>
<p><strong>Objetivo general</strong>: Analizar los principales determinantes individuales y contextuales de la alfabetización digital en estudiantes al año 2023 y cómo se diferencian entre países</p>
<p><strong>Hipótesis de nivel 1</strong></p>
<p><span class="math inline">\(H_1\)</span>: Las mujeres tendrán mayor puntaje de alfabetización digital que los hombres</p>
<p><span class="math inline">\(H_2\)</span>: El nivel socioeconómico se asociará positivamente con la alfabetización digital</p>
<p><span class="math inline">\(H_3\)</span>: A mayor nivel de autoeficacia digital del estudiante, mayor será su puntaje en alfabetización digital</p>
<p><strong>Hipótesis de nivel 2</strong></p>
<p><span class="math inline">\(H_4\)</span>: Pertenecer a un país con mayor índice de administración digital tiene un efecto positivo sobre la alfabetización digital de los estudiantes</p>
<p><span class="math inline">\(H_5\)</span>: A mayor PIB per cápita, los estudiantes tendrán un puntaje más alto de alfabetización digital</p>
<p><strong>Hipótesis de interacción</strong></p>
<p><span class="math inline">\(H_6\)</span> El efecto positivo del nivel socioeconómico sobre la alfabetización digital es más intenso en países con menor PIB per cápita</p>
</section></section><section id="datos-variables-y-métodos" class="level1" data-number="4"><h1 data-number="4">
<span class="header-section-number">4</span> Datos, variables y métodos</h1>
<p>Para dar una respuesta plausible a la pregunta de investigación, el presente estudio se sirve de la base de datos del último ciclo del <a href="https://www.iea.nl/studies/iea/icils/2023">International Computer and Information Literacy Study</a> (ICILS) llevado a cabo el año 2023, aplicada en 35 países (N = 135615). Esta base, además de aplicar encuestas de caracterización, realiza una prueba práctica estandarizada para cumplir con la medición de la alfabetización digital. En este caso, se van a utilizar las bases de datos de estudiantes, la cual, después de haber sido procesada tiene N = 104991 anidados en 31 países. El diseño muestral es complejo por conglomerados multietápicos. Por último, es pertinente mencionar que la unidad de análisis son los estudiantes correspondientes al octavo año de escolarización.</p>
<p>A modo auxiliar, para incluir datos a nivel país se utilizaron las bases de datos Quality of Government y la del Banco Mundial.</p>
<section id="variables" class="level2" data-number="4.1"><h2 data-number="4.1" class="anchored" data-anchor-id="variables">
<span class="header-section-number">4.1</span> Variables</h2>
<p><strong>Variable dependiente</strong></p>
<p>Alfabetización digital: La variable dependiente de este estudio es el logro de alfabetización digital medido a través de una prueba compuesta por cuatro módulos, de los cuales los estudiantes sólo respondieron dos seleccionados de manera aleatoria. La variable puede tomar 5 valores plausibles a partir del puntaje logrado por los estudiantes: Bajo del nivel 1 (menos de 407 puntos), Nivel 1 (desde 407 hasta 491 puntos), Nivel 2 (desde 492 hasta 576 puntos), Nivel 3 (desde 557 hasta 661 puntos) y el Nivel 4 (sobre 661 puntos).</p>
<p><strong>Variables nivel 1</strong></p>
<p>Sexo: Esta variable puede tener dos valores: 0 para hombre y 1 para mujer.</p>
<p>Autoeficacia: Para medir la autoeficacia, se emplearon dos dimensiones: autoeficacia relacionada al uso general de aplicaciones y autoeficacia relacionada al uso especializado de aplicaciones. Cada una de ellas es un índice construido a partir de distintos enunciados relacionados a la autopercepción del estudiante respecto a qué tan bien puede desempeñar una labor usando TIC. Ambas autoeficacias poseen cuatro categorías de respuesta: (1) Muy bien; (2) Moderadamente bien; (3) Nunca he hecho esto, pero podría descubrir cómo hacerlo; (4) No creo que pueda hacer esto.</p>
<p>Índice socioeconómico: Mide el nivel socioecómico del estudiante a partir del estatus ocupacional más alto de los padres, el nivel educativo más alto de los padres y el número de libros en casa.</p>
<p>Experiencia con computador en años (expcompu): Mide la cantidad de años de experiencia que posee un estudiante con computador a través de cinco categorías de respuesta. (0) Nunca o menos de un año; (1) Al menos un año pero menos que tres; (2) Al menos tres años pero menos que cinco; (3) Al menos cinco años pero menos que siete; (4) Siete años o más.</p>
<p>Tareas relacionadas al aprendizaje online en la escuela: Es una variable construida a partir de una serie de indicadores que refieren a si el estudiante realizó la respectiva actividad en su escuela.</p>
<p>Cabe precisar que tanto Experiencia con computador en años como Tareas relacionadas al aprendizaje online en la escuela serán utilizadas como variables de control.</p>
<div class="cell" data-tbl-cap-location="bottom">
<div id="tbl-descr1" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap-location="bottom">
<figure class="quarto-float quarto-float-tbl figure"><div aria-describedby="tbl-descr1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">var</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">label</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">NA.prc</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">range</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">alf_digital</td>
<td style="text-align: left;">Puntaje de alfabetización digital</td>
<td style="text-align: right;">104991</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">491.16</td>
<td style="text-align: right;">91.68</td>
<td style="text-align: left;">724.7 (45.41-770.12)</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">aprendizaje_escuela</td>
<td style="text-align: left;">Tareas relacionadas al aprendizaje online en la escuela</td>
<td style="text-align: right;">104991</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">49.95</td>
<td style="text-align: right;">10.04</td>
<td style="text-align: left;">54.99 (20.76-75.75)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">autoeffgen</td>
<td style="text-align: left;">Autoeficacia digital general del estudiante</td>
<td style="text-align: right;">104991</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">50.07</td>
<td style="text-align: right;">9.93</td>
<td style="text-align: left;">51.5 (26.62-78.12)</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">sexo</td>
<td style="text-align: left;">Sexo de estudiante</td>
<td style="text-align: right;">104991</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: left;">1 (0-1)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: left;">expcompu</td>
<td style="text-align: left;">Experiencia con computador en años</td>
<td style="text-align: right;">104991</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.50</td>
<td style="text-align: right;">1.27</td>
<td style="text-align: left;">4 (0-4)</td>
</tr>
<tr class="even">
<td style="text-align: left;">5</td>
<td style="text-align: left;">iiseb</td>
<td style="text-align: left;">Índice Socioeconómico Internacional</td>
<td style="text-align: right;">104991</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: left;">4.46 (-2.54-1.91)</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-descr1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;1: Variables nivel 1
</figcaption></figure>
</div>
</div>
<p><strong>Variables nivel 2</strong></p>
<p>Gobernanza digital: Es una media ponderada de puntajes normalizados extraído de Quality of Government, el cual está construido a partir de un índice de servicios online, un índice del estado de desarrollo de infraestructura en telecomunicaciones y un índice de capital humano. Sus valores van del 0 al 1, donde los valores más cercanos al 1 significan mayor capacidad de gobernanza digital.</p>
<p>PIB per cápita: Es un indicador que representa el valor promedio de bienes y servicios producidos por cada persona en un país o territorio durante un período determinado. Se calcula dividiendo el PIB total de un país por la cantidad total de habitantes. Está expresado en dólares.</p>
<p>Logaritmo del PIB: Es la misma variable de PIB per cápita pero calculando su logaritmo, pues esto permite que se ajusten los pesos del valor para cada país, facilitando su interpretación.</p>
<div class="cell" data-tbl-cap-location="bottom">
<div id="tbl-descr2" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap-location="bottom">
<figure class="quarto-float quarto-float-tbl figure"><div aria-describedby="tbl-descr2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">var</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">label</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">NA.prc</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sd</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">range</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">adm_digital</td>
<td style="text-align: left;">Administración digital</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.84</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: left;">0.34 (0.64-0.98)</td>
</tr>
<tr class="even">
<td style="text-align: left;">logpib</td>
<td style="text-align: left;">Logaritmo de PIB</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3.45</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: left;">2.89 (1.96-4.86)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">pib</td>
<td style="text-align: left;">Producto Interno Bruto per cápita</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">38.88</td>
<td style="text-align: right;">26.65</td>
<td style="text-align: left;">121.55 (7.13-128.68)</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-descr2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;2: Variables nivel 2
</figcaption></figure>
</div>
</div>
</section><section id="métodos" class="level2" data-number="4.2"><h2 data-number="4.2" class="anchored" data-anchor-id="métodos">
<span class="header-section-number">4.2</span> Métodos</h2>
<p>Para esta investigación se pretende emplear modelos multinivel para realizar un análisis comparado entre los distintos países que conforman el estudio. Una de las razones por las que se opta este método es debido a la capacidad de estudiar estructuras de datos jerárquicos de la población <span class="citation" data-cites="hox_multilevel_2017">(<a href="#ref-hox_multilevel_2017" role="doc-biblioref">Hox 2017</a>)</span>. De esta manera, los modelos multinivel permiten complejizar los análisis en tanto pueden ayudar a comprender relaciones entre variables de tipo individual con variables de tipo contextual. Esta técnica de análisis generalmente se utiliza para observar datos anidados, por lo cual se estima ideal para el desarrollo de este trabajo en tanto se estudiarán datos de estudiantes que se hallan dentro de países.</p>
<p>Los modelos serán reportados en el siguiente orden:</p>
<p><strong>1) Modelo nulo</strong></p>
<p><span class="math display">\[\text{alf\_digital}_{ij} = \gamma_{00} + \mu_{0j} + r_{ij}\]</span> <strong>2) Modelo con predictores individuales</strong></p>
<p><span class="math display">\[
\begin{multline}
\text{alf\_digital}_{ij} = \gamma_{00} + \gamma_{10} \text{sexo}_{ij} + \gamma_{20} \text{iiseb}_{ij} + \gamma_{30} \text{expcompu}_{ij} + \gamma_{40} \text{autoeffgen}_{ij} \\
+ \gamma_{50} \text{aprendizaje\_escuela}_{ij} + \mu_{0j} + r_{ij}
\end{multline}
\]</span> <strong>3) Modelo con predictores grupales</strong></p>
<p><span class="math display">\[\text{alf\_digital}_{ij} = \gamma_{01} \text{adm\_digital}_{ij} + \gamma_{02} \text{logpib}_{ij} + \mu_{0j} + r_{ij}\]</span> <strong>4) Modelo con predictores individuales y grupales</strong></p>
<p><span class="math display">\[
\begin{multline}
\text{alf\_digital}_{ij} = \gamma_{00} + \gamma_{10} \text{sexo}_{ij} + \gamma_{20} \text{iiseb}_{ij} + \gamma_{30} \text{expcompu}_{ij} + \gamma_{40} \text{autoeffgen}_{ij} \\
+ \gamma_{50} \text{aprendizaje\_escuela}_{ij} + \gamma_{01} \text{adm\_digital}_{ij} + \gamma_{02} \text{logpib}_{ij} + \mu_{0j} + r_{ij}
\end{multline}
\]</span></p>
<p><strong>5) Modelo con pendiente aleatoria</strong></p>
<p><span class="math display">\[\text{alf\_digital}_{ij} = \gamma_{00} + \gamma_{20} \text{iiseb}_{ij} + \gamma_{02} \text{logpib}_{ij} + \mu_{1j}\text{iiseb}_{ij} + \mu_{0j} + r_{ij}\]</span></p>
<p><strong>6) Interacción entre niveles</strong></p>
<p><span class="math display">\[\text{alf\_digital}_{ij} = \gamma_{00} +  \gamma_{20} \text{iiseb}_{ij} + \gamma_{02} \text{logpib}_{ij} + \gamma_{11}\text{iiseb}_{ij} \text{logpib}_{ij} + \mu_{1j}\text{iiseb}_{ij} + \mu_{0j} + r_{ij}\]</span></p>
</section></section><section id="resultados" class="level1" data-number="5"><h1 data-number="5">
<span class="header-section-number">5</span> Resultados</h1>
<section id="descriptivos" class="level2" data-number="5.1"><h2 data-number="5.1" class="anchored" data-anchor-id="descriptivos">
<span class="header-section-number">5.1</span> Descriptivos</h2>
<div class="cell fig-cap-location-bottom">
<details class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb1" data-cap-location="bottom"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">scatter</span> <span class="op">&lt;-</span> <span class="va">icils</span> <span class="op">%&gt;%</span> <span class="fu">group_by</span><span class="op">(</span><span class="va">CNTRY</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu">select</span><span class="op">(</span><span class="va">alf_digital</span>, <span class="va">adm_digital</span>, <span class="va">logpib</span>, <span class="va">pib</span><span class="op">)</span> <span class="op">%&gt;%</span>   <span class="fu"><a href="https://rdrr.io/r/stats/na.fail.html">na.omit</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">summarise_all</span><span class="op">(</span><span class="va">mean</span><span class="op">)</span> <span class="co"># base para visualizar el scatterplot</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">scatter</span><span class="op">$</span><span class="va">alf_digital</span>, <span class="va">scatter</span><span class="op">$</span><span class="va">logpib</span><span class="op">)</span> <span class="co"># calcular correlación </span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre data-cap-location="bottom"><code>[1] 0.6596024</code></pre>
</div>
<details class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb3" data-cap-location="bottom"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">sjPlot</span><span class="fu">::</span><span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_scatter.html">plot_scatter</a></span><span class="op">(</span><span class="va">scatter</span>, <span class="va">logpib</span>, <span class="va">alf_digital</span>,</span>
<span>            dot.labels <span class="op">=</span> <span class="fu">to_label</span><span class="op">(</span><span class="va">scatter</span><span class="op">$</span><span class="va">CNTRY</span><span class="op">)</span>,</span>
<span>            fit.line <span class="op">=</span> <span class="st">"lm"</span>,</span>
<span>            show.ci <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>            axis.titles <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Producto Interno Bruto per cápita (log)"</span>,</span>
<span>            <span class="st">"Alfabetización digital"</span><span class="op">)</span>,</span>
<span>            colors <span class="op">=</span> <span class="st">"#7b241c"</span></span>
<span>            <span class="op">)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div id="fig-scarlogpib" class="quarto-float quarto-figure quarto-figure-center anchored" data-cap-location="bottom">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-scarlogpib-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Entrega-final-multinivel_files/figure-html/fig-scarlogpib-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scarlogpib-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Correlación alfabetización digital y PIB(log) (r = 0.66)
</figcaption></figure>
</div>
</div>
</div>
<p>En <a href="#fig-scarlogpib" class="quarto-xref">Figura&nbsp;1</a> se observa la correlación entre alfabetización digital y el logaritmo de PIB per cápita. La correlación entre ambas variables es positiva y con un efecto fuerte. En general, los países se ven dipersos conforme a la recta, lo que significa que a mayor PIB per cápita, mayor alfabetización digital. Aun así, es interesante observar casos como los de Korea y República Checa, que son los dos países que tienen el promedio de alfabetización digital más alto pero no son aquellos con el mayor PIB per cápita.</p>
<div class="cell fig-cap-location-bottom">
<details class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb4" data-cap-location="bottom"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/cor.html">cor</a></span><span class="op">(</span><span class="va">scatter</span><span class="op">$</span><span class="va">alf_digital</span>, <span class="va">scatter</span><span class="op">$</span><span class="va">adm_digital</span><span class="op">)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre data-cap-location="bottom"><code>[1] 0.5583879</code></pre>
</div>
<details class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb6" data-cap-location="bottom"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">sjPlot</span><span class="fu">::</span><span class="fu"><a href="https://strengejacke.github.io/sjPlot/reference/plot_scatter.html">plot_scatter</a></span><span class="op">(</span><span class="va">scatter</span>, <span class="va">adm_digital</span>, <span class="va">alf_digital</span>,</span>
<span>            dot.labels <span class="op">=</span> <span class="fu">to_label</span><span class="op">(</span><span class="va">scatter</span><span class="op">$</span><span class="va">CNTRY</span><span class="op">)</span>,</span>
<span>            fit.line <span class="op">=</span> <span class="st">"lm"</span>,</span>
<span>            show.ci <span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>            axis.titles <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Administración digital"</span>,</span>
<span>            <span class="st">"Alfabetización digital"</span><span class="op">)</span>,</span>
<span>            colors <span class="op">=</span> <span class="st">"#7b241c"</span></span>
<span>            <span class="op">)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div id="fig-scaradm" class="quarto-float quarto-figure quarto-figure-center anchored" data-cap-location="bottom">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-scaradm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Entrega-final-multinivel_files/figure-html/fig-scaradm-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scaradm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;2: Correlación alfabetización digital y administración digital (r = 0.56)
</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-scaradm" class="quarto-xref">Figura&nbsp;2</a> Representa la correlación entre alfabetización digital y administración digital, la cual tiene un efecto positivo y moderado. Se puede apreciar que la mayoría de los países se concentran entre el 0.8 y 0.9, lo cual es bastante alto tomando en cuenta que el índice va desde 0 a 1. Llama la atención Dinamarca que, si bien su puntaje de administración digital es 0.98, siendo el país que puntúa más alto, en el gráfico se muestra sobrepasando el valor 1. En segundo lugar está Korea, lo cual es consistente con el resultado de la correlación.</p>
</section><section id="modelos" class="level2" data-number="5.2"><h2 data-number="5.2" class="anchored" data-anchor-id="modelos">
<span class="header-section-number">5.2</span> Modelos</h2>
<p>El reporte de los modelos será presentado en el mismo orden de la formalización de las ecuaciones. En orden de precisar las estimaciones de los modelos, las variables de nivel individual fueron centradas al grupo (CMC).</p>
<div style="overflow-x: auto; width: 100%;">
<div class="cell">
<div id="tbl-models" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;3: Modelos
</figcaption><div aria-describedby="tbl-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table style="font-size: 20px;">
<tbody><tr>
<th style="border-top: double; text-align:center; font-style:italic; font-weight:normal; padding:0.2cm; border-bottom:1px solid black; text-align:left; ">&nbsp;</th>
<th colspan="1" style="border-top: double; text-align:center; font-style:italic; font-weight:normal; padding:0.2cm; border-bottom:1px solid black;">Modelo nulo</th>
<th colspan="1" style="border-top: double; text-align:center; font-style:italic; font-weight:normal; padding:0.2cm; border-bottom:1px solid black;">Variables nivel 1</th>
<th colspan="1" style="border-top: double; text-align:center; font-style:italic; font-weight:normal; padding:0.2cm; border-bottom:1px solid black;">Administración digital</th>
<th colspan="1" style="border-top: double; text-align:center; font-style:italic; font-weight:normal; padding:0.2cm; border-bottom:1px solid black;">Variables nivel 2</th>
<th colspan="1" style="border-top: double; text-align:center; font-style:italic; font-weight:normal; padding:0.2cm; border-bottom:1px solid black;">Modelo completo</th>
<th colspan="1" style="border-top: double; text-align:center; font-style:italic; font-weight:normal; padding:0.2cm; border-bottom:1px solid black;">Pendiente aleatoria</th>
<th colspan="1" style="border-top: double; text-align:center; font-style:italic; font-weight:normal; padding:0.2cm; border-bottom:1px solid black;">Interacción entre niveles</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal; border-bottom:1px solid black; text-align:left; ">Predictors</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal; border-bottom:1px solid black; ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal; border-bottom:1px solid black; ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal; border-bottom:1px solid black; ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal; border-bottom:1px solid black; ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal; border-bottom:1px solid black; ">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal; border-bottom:1px solid black; col7">Estimates</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal; border-bottom:1px solid black; col8">Estimates</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">(Intercept)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">489.12 <sup>***</sup><br>(7.52)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">489.12 <sup>***</sup><br>(7.52)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">231.76 <sup>**</sup><br>(71.29)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">310.77 <sup>***</sup><br>(72.37)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">310.78 <sup>***</sup><br>(72.36)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">342.77 <sup>***</sup><br>(30.02)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">347.44 <sup>***</sup><br>(29.54)</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Sexo de estudiante</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">15.18 <sup>***</sup><br>(0.46)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">15.18 <sup>***</sup><br>(0.46)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8"></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Índice Socioeconómico<br>Internacional</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">26.06 <sup>***</sup><br>(0.24)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">26.06 <sup>***</sup><br>(0.24)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">28.62 <sup>***</sup><br>(0.96)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">25.39 <sup>***</sup><br>(4.99)</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Experiencia con<br>computador en años</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">10.14 <sup>***</sup><br>(0.19)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">10.14 <sup>***</sup><br>(0.19)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8"></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Autoeficacia digital<br>general del estudiante</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.33 <sup>***</sup><br>(0.03)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.33 <sup>***</sup><br>(0.03)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8"></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Tareas relacionadas al<br>aprendizaje online en la<br>escuela</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.06 <sup>*</sup><br>(0.02)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">0.06 <sup>*</sup><br>(0.02)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8"></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">Administración digital</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">306.91 <sup>***</sup><br>(84.68)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">68.20 <sup></sup><br>(121.71)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">68.18 <sup></sup><br>(121.71)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8"></td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">PIB per cápita(log)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">35.12 <sup>*</sup><br>(13.79)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">35.12 <sup>*</sup><br>(13.79)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">42.45 <sup>***</sup><br>(8.53)</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">41.07 <sup>***</sup><br>(8.41)</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">iiseb.cmc:logpib</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  "></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7"></td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col8">0.95 <sup></sup><br>(1.42)</td>
</tr>
<tr>
<td colspan="8" style="font-weight:bold; text-align:left; padding-top:.8em;">Random Effects</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">σ<sup>2</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">6592.96</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">5654.32</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">6592.96</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">6592.96</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">5654.32</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">5854.25</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">5854.24</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">τ<sub>00</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">1752.50 <sub>CNTRY</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">1752.77 <sub>CNTRY</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">1247.12 <sub>CNTRY</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">1048.34 <sub>CNTRY</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">1048.60 <sub>CNTRY</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">1039.79 <sub>CNTRY</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">957.86 <sub>CNTRY</sub>
</td>

</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">τ<sub>11</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">&nbsp;</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">&nbsp;</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">&nbsp;</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">&nbsp;</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">&nbsp;</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">26.12 <sub>CNTRY.iiseb</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">24.87 <sub>CNTRY.iiseb.cmc</sub>
</td>

</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">ρ<sub>01</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">&nbsp;</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">&nbsp;</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">&nbsp;</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">&nbsp;</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">&nbsp;</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">-0.24 <sub>CNTRY</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">-0.23 <sub>CNTRY</sub>
</td>

</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">ICC</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">0.21</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">0.24</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">0.16</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">0.14</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">0.16</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">0.15</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">0.14</td>

</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">N</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">31 <sub>CNTRY</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">31 <sub>CNTRY</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">31 <sub>CNTRY</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">31 <sub>CNTRY</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">31 <sub>CNTRY</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">31 <sub>CNTRY</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">31 <sub>CNTRY</sub>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">Observations</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center; border-top:1px solid;" colspan="1">104991</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center; border-top:1px solid;" colspan="1">104991</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center; border-top:1px solid;" colspan="1">104991</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center; border-top:1px solid;" colspan="1">104991</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center; border-top:1px solid;" colspan="1">104991</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center; border-top:1px solid;" colspan="1">104991</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center; border-top:1px solid;" colspan="1">104991</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">Marginal R<sup>2</sup> / Conditional R<sup>2</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">0.000 / 0.210</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">0.112 / 0.322</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">0.050 / 0.201</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">0.073 / 0.201</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">0.187 / 0.314</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">0.171 / 0.296</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:center;" colspan="1">0.168 / 0.287</td>
</tr>
<tr>
<td colspan="8" style="font-style:italic; border-top:double black; text-align:right;">* p&lt;0.05&nbsp;&nbsp;&nbsp;** p&lt;0.01&nbsp;&nbsp;&nbsp;*** p&lt;0.001</td>
</tr>
</tbody></table>
</div>
</div>
</figure>
</div>
</div>
</div>
<section id="modelo-nulo" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="modelo-nulo"><strong>Modelo nulo</strong></h3>
<p>El primer modelo estimado fue el modelo nulo, puesto que permite calcular el ICC y determinar si es pertinente usar modelamiento multinivel en el análisis. A partir de <span class="math inline">\(\tau_{00}\)</span> / <span class="math inline">\(\tau_{00}\)</span> + <span class="math inline">\(\sigma^2\)</span> el ICC dio 0.21, lo que significa que el 21% de la varianza de la alfabetización digital se debe a la pertenencia a países. Este resultado es significativo, por lo que se justifica la aplicación de modelos multinivel para indagar en las diferencias de alfabetización digital de estudiantes anidados en países.</p>
</section><section id="modelo-con-predictores-individuales" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="modelo-con-predictores-individuales"><strong>Modelo con predictores individuales</strong></h3>
<p>El segundo modelo de <a href="#tbl-models" class="quarto-xref">Tabla&nbsp;3</a> es el que contiene los predictores de nivel uno. Este modelo sirve para contrastar las hipótesis <span class="math inline">\(H_1\)</span>, <span class="math inline">\(H_2\)</span> y <span class="math inline">\(H_3\)</span> que serán discutidas más adelante.</p>
<p>Todas las variables son estadísticamente significativas, por lo que de momento no se puede descartar ninguna hipótesis, pues todas aportan en la predicción de la alfabetización digital.</p>
<p>Respecto a los coeficientes, considerando que todos los estudiantes tienen la misma experiencia en computadores en años, y todos realizan las mismas tareas con TIC en la escuela, las mujeres puntúan en promedio 15.18 más alto que los hombres. Tener un punto adicional en nivel socioeconómico aumenta el puntaje de alfabetización digital en 26.06. Por último, cada unidad adicional en autoeficacia digital aumenta un 0.33 la alfabetización digital de los estudiantes.</p>
<p>Se puede apreciar que todos los efectos son positivos, y tanto sexo como nivel socioeconómico tienen efectos bastante grandes en comparación con el de autoeficacia digital.</p>
<p>En cuanto a los efectos aleatorios, se observa que, en comparación al modelo nulo, <span class="math inline">\(\sigma^2\)</span> pasa de 6592.96 a 5654.32, por lo que se puede asumir que el modelo con predictores individuales permite capturar parte de la variabilidad existente dentro de los países.</p>
</section><section id="modelo-con-predictores-grupales" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="modelo-con-predictores-grupales"><strong>Modelo con predictores grupales</strong></h3>
<p>El tercer y cuarto modelo expuesto en <a href="#tbl-models" class="quarto-xref">Tabla&nbsp;3</a> contienen los predictores grupales. El primero de estos dos modelos solamente considera la variable de administración digital y no fue especificado en las ecuaciones previas, pero esto se debe a que fue estimado solamente para efectos ilustrativos, pues ocurre algo interesante entre las variables a nivel país.</p>
<p>Al ingresar administración digital a un modelo, se ve que es estadísticamente significativa con un efecto muy grande, lo cual señala que, un país con la mejor calidad en administración digital tendría 306.91 puntos adicionales en alfabetización digital en comparación a un país con la más precaria administración digital.</p>
<p>Sin embargo, al ingresar PIB per cápita (expresado en su lograritmo) al modelo, la administración digital pierde toda su significancia, y su efecto disminuye considerablemente a 68.20. En paralelo, el PIB es significativo pero moderadamente, donde por cada mil dólares adicionales, la alfabetización digital aumenta en 35.12. Este resultado llama bastante la atención, pero se puede comprender por la parcialización de las variables al momento de estimarse la regresión, entendiéndose que el efecto del PIB per cápita predomina por sobre el de la administración digital al predecir la alfabetización digital.</p>
<p>En relación a los efectos aleatorios, se aprecia una disminución del <span class="math inline">\(\tau_{00}\)</span> a 1048.34, cuyo resultado indica que parte de las diferencias entre países se explica por el PIB per cápita.</p>
</section><section id="modelo-completo" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="modelo-completo"><strong>Modelo completo</strong></h3>
<p>Este modelo incluye tanto los predictores individuales como los grupales, por lo que se pueden contrastar las cinco hipótesis planteadas anteriormente solamente analizando este modelo.</p>
<p>Se observa que todos los coeficientes mantienen sus valores al igual que sus efectos significativos.</p>
<p>Algo llamativo es el incremento, pero muy leve, de <span class="math inline">\(\tau_{00}\)</span> a 1048.60.</p>
</section><section id="modelo-pendiente-aleatoria" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="modelo-pendiente-aleatoria"><strong>Modelo pendiente aleatoria</strong></h3>
<div class="cell">
<details class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">reg_1</span> <span class="op">&lt;-</span> <span class="fu">lmer</span><span class="op">(</span><span class="va">alf_digital</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">+</span> <span class="va">iiseb.cmc</span> <span class="op">+</span> <span class="va">logpib</span> <span class="op">+</span> <span class="op">(</span><span class="fl">1</span> <span class="op">|</span> <span class="va">CNTRY</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">icils_c</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">reg_1</span>, <span class="va">reg_random</span><span class="op">)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Data: icils_c
Models:
reg_1: alf_digital ~ 1 + iiseb.cmc + logpib + (1 | CNTRY)
reg_random: alf_digital ~ 1 + iiseb.cmc + logpib + (1 + iiseb | CNTRY)
           npar     AIC     BIC  logLik deviance  Chisq Df
reg_1         5 1209312 1209360 -604651  1209302          
reg_random    7 1209026 1209093 -604506  1209012 289.84  2
                      Pr(&gt;Chisq)    
reg_1                               
reg_random &lt; 0.00000000000000022 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>El modelo con pendiente aleatoria para nivel socioeconómico pretende averiguar si esta variable varía entre países. Calculando un test de devianza entre el modelo con pendiente fija y aleatoria, resultó que el modelo con pendiente aleatoria ajusta significativamente mejor que el otro, presentando un <span class="math inline">\(\chi^2\)</span> = 289.84, por lo que se comprueba que el efecto del nivel socioeconómico en la alfabetización digital no es el mismo entre países.</p>
<p><span class="math inline">\(\tau_{11}\)</span> = 26.12 respalda que el efecto del nivel socioeconómico no es el mismo para todos los países. Por su parte, <span class="math inline">\(\rho_{01}\)</span> = -0.24 indica que, en países con menor alfabetización digital, el efecto del nivel socioeconómico es más fuerte.</p>
<div class="cell">
<details class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">graf2</span> <span class="op">&lt;-</span> <span class="fu">ggpredict</span><span class="op">(</span></span>
<span>  <span class="va">reg_random</span>, </span>
<span>  terms <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"iiseb"</span>, <span class="st">"CNTRY [CHL, URY, ROU, AZE, GRC, FIN]"</span><span class="op">)</span>, </span>
<span>  type <span class="op">=</span> <span class="st">"random"</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">graf2</span><span class="op">)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="Entrega-final-multinivel_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Este gráfico corresponde a la aleatorización de las pendientes de nivel socioeconómico. En primer lugar, se observa que las pendientes difieren unas entre otras, por lo que añadir efectos aleatorios es una decisión acertada. Los dos países latinoamericanos que participan en el estudio, Uruguay y Chile, tienen una pendiente positiva bastante similar. Por otro lado, la pendiente de Rumanía es bastante alta, lo que significa que el efecto de nivel socioeconómico sobre la alfabetización digital en ese país es fuerte.</p>
</section><section id="modelo-interacción-entre-niveles" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="modelo-interacción-entre-niveles"><strong>Modelo interacción entre niveles</strong></h3>
<div class="cell fig-cap-location-bottom">
<div class="cell-output-display">
<div id="fig-interaction" class="quarto-float quarto-figure quarto-figure-center anchored" data-cap-location="bottom">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-interaction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Entrega-final-multinivel_files/figure-html/fig-interaction-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-interaction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3: Interacción entre índice socioeconómico y alfabetización digital
</figcaption></figure>
</div>
</div>
</div>
<p>A pesar de mantenerse con coeficientes significativos, al momento de graficar la interacción, en <a href="#fig-interaction" class="quarto-xref">Figura&nbsp;3</a> las dos pendientes no se intersectan, lo que quiere decir que no se ha encontrado una interacción entre nivel socioeconómico y PIB per cápita para predecir la alfabetización digital.</p>
</section></section><section id="ajuste" class="level2" data-number="5.3"><h2 data-number="5.3" class="anchored" data-anchor-id="ajuste">
<span class="header-section-number">5.3</span> Ajuste</h2>
<p>Respecto al ajuste de los modelos, se puede ver que, en el modelo de variables individuales, el <span class="math inline">\(r^2\)</span> condicional es mayor al <span class="math inline">\(r^2\)</span> marginal (0.332 &gt; 0.112), lo que quiere decir que el modelo con efectos aleatorios posee una mayor capacidad explicativa que el modelo con efectos fijos. El modelo con solamente variables contextuales también tiene un mejor ajuste en el <span class="math inline">\(r^2\)</span> condicional, respaldando la estimación de un modelo con efectos aleatorios. El resultado más llamativo es el ajuste del modelo completo, en donde el <span class="math inline">\(r^2\)</span> condicional, si bien es mejor que su <span class="math inline">\(r^2\)</span> marginal (0.314 &gt; 0.187), es más bajo que el <span class="math inline">\(r^2\)</span> condicional del modelo con variables individuales. No obstante, esto no quiere decir necesariamente que el modelo con variables nivel 1 tenga mayor capacidad explicativa que el modelo completo, pero habría que entrar a escarbar de manera minuciosa para comprender a cabalidad la razón de este resultado.</p>
</section><section id="casos-influyentes" class="level2" data-number="5.4"><h2 data-number="5.4" class="anchored" data-anchor-id="casos-influyentes">
<span class="header-section-number">5.4</span> Casos influyentes</h2>
<p>Para analizar la existencia de casos influyentes, se estimó la distancia de Cook a partir del modelo completo, de la cual resultó un cutoff de 0.13, entendiéndose que todos los países sobre ese umbral podrían ser casos que están modificando sustancialmente las estimaciones de los modelos.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          [,1]
FIN 0.01963481
SWE 0.03450031
DNK 0.04727367
CHL 0.05151190
SRB 0.06139562
NLD 0.06637431
LVA 0.10406601
GRC 0.10762657
BIH 0.10825537
AUT 0.11733263
URY 0.12515838
DEU 0.13505330
ITA 0.13573523
SVK 0.13844328
PRT 0.14873691
FRA 0.15224779
CYP 0.16548448
MLT 0.18043342
USA 0.20465886
HRV 0.21766717
ROU 0.21890219
SVN 0.22732826
KOR 0.31667474
HUN 0.33872546
KAZ 0.36080784
NOR 0.42509142
CZE 0.49036851
AZE 0.53666770
LUX 0.58994701
ESP 1.13527869
OMN 1.79270343</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1290323</code></pre>
</div>
</div>
<div class="cell fig-cap-location-bottom">
<div class="cell-output-display">
<div id="fig-cook" class="quarto-float quarto-figure quarto-figure-center anchored" data-cap-location="bottom">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-cook-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Entrega-final-multinivel_files/figure-html/fig-cook-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cook-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4: Distancia de Cook
</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-cook" class="quarto-xref">Figura&nbsp;4</a> grafica los países que son considerados como casos influyentes con rojo, mientras que los azules significa que no están interfiriendo en las estimaciones. Como se observa, más de la mitad de los países están por sobre 0.13, lo cual podría ser peligroso para el análisis pues, en algún caso, se podría decidir eliminar todos los países en rojo. No obstante, calculando la significancia de los casos, ninguno resultó como significante, por lo que se puede interpretar que no se puede asumir que los países en rojo sean casos influyentes.</p>
</section></section><section id="discusión" class="level1" data-number="6"><h1 data-number="6">
<span class="header-section-number">6</span> Discusión</h1>
<p>En relación a las hipótesis de carácter individual, hay evidencia a favor de <span class="math inline">\(H_1\)</span>, señalando que las mujeres tienen puntajes más altos en alfabetización digital en comparación a sus contrapartes. Este resultado se condice con la literatura actual, cuyo argumento central radica en que las mujeres se hallan a la vanguardia del logro académico, revirtiendo un panorama históricamente a favor de su contraparte masculina. Este hallazgo hay que considerarlo pero con suma precaucion, pues no debe interpretarse como el punto culmine de las desigualdades de género. En suma, no significa que el estigma sobre las mujeres en este campo se haya desmantelado, pero al menos se está avanzando en algunas materias en orden de equilibrar esta balanza social en lo que respecta al género</p>
<p>De la misma manera, el nivel socioeconómico (<span class="math inline">\(H_2\)</span>) es significativa, por tanto, tener un alto nivel socioeconómico se relaciona a un alto puntaje en alfabetización digital. Este efecto se entronca en la narrativa general de cómo el desempeño académico se ve predicho por los antecedentes socioeconomicos del estudiante. Esto resulta desalentador, pues se esperaría que con las condiciones actuales (disponibilidad de tecnologías de alto rendimiento) este efecto se mitigara, pero probablemente las escuelas aun no son o, en el peor de los casos, no serán capaces de ofrecer alternativas para sortear las desigualdades economicas de base de los estudiantes. Este resultado respalda la escuela en una lógica reproduccionista, pues el nivel socioeconómico es lo que regirá los resultados, reduciendo el margen de la agencia y/o talento de los estudiantes más desfavorecidos económicamente hablando.</p>
<p>La autoeficacia digital (<span class="math inline">\(H_3\)</span>) no puede ser rechazada pues es significativa y mantiene la direccionalidad sugerida en las hipótesis, por lo tanto, tener alta autoeficacia digital se relaciona a un mayor puntaje en alfabetización digital. Es sumamente interesante el resultado de esta hipótesis, pues releva la consideración de factores psicosociales en el logro académico en el contexto digital. Si bien es importante preparar a los estudiantes para que manejen los conocimientos prácticos y puedan tener un desempeño destacable, la valorización hacia uno mismo y sus capacidades juega un papel igual de notable. Por ello, hay que fomentar tanto el perfeccionamiento de las habilidades como el forjamiento de un autoestima sólido en los estudiantes, para que, de esta forma, puedan explotar sus capacidades sin restringirse.</p>
<p>En cuanto a las hipótesis de nivel país, la administración digital (<span class="math inline">\(H_4\)</span>) no tiene sustento empírico, pues no es significativo, por lo que se puede deducir que el hecho de que un país tenga alta o baja administración digital, no influirá en la alfabetización digital de sus estudiantes.</p>
<p>El PIB per cápita (<span class="math inline">\(H_5\)</span>) muestra que es significativo y posee un efecto positivo en la alfabetización digital, por lo que países con mayor riqueza tenderán a resultados más altos en este campo.</p>
<p>A partir de las dos últimas hipótesis se puede deducir que, la masterización de habilidades digitales, más que deberse a un país con infraestructura tecnológica eficiente, se atribuye a las condiciones que permite generar la riqueza del país, es decir, la capacidad de una administración digital a nivel gubernamental se subsume al entramado que un país puede configurar a partir de las condiciones económicas propias. En este sentido, la gobernanza digital es contenida en este entramado, el cual podría además abordar elementos de la esfera social, política y cultural, pero hace falta evidencia para entregar un diagnóstico más claro.</p>
</section><section id="conclusiones" class="level1" data-number="7"><h1 data-number="7">
<span class="header-section-number">7</span> Conclusiones</h1>
<p>Esta investigación tenía como objetivo analizar los factores individuales y contextuales a nivel país de la alfabetización digital en estudiantes. Respondiendo a la pregunta planteada al inicio, dentro de los hallazgos más importantes se encuentra la evidencia empírica de que sexo y nivel socioeconómico a nivel individual determinan la alfabetización digital de los estudiantes. A partir de la pendiente aleatoria, se pudo deducir que el efecto de nivel socioeconómico es distinto dependiendo del país, lo que también justifica de gran manera la utilización de modelamiento multinivel. El hallazgo más interesante fue la parcialización de administración digital y PIB per cápita, en donde el PIB terminó restándole toda la significancia previa que tenía la gobernanza digital. Este hallazgo permitió concluir que la riqueza de un país es lo que determina las habilidades y conocimientos digitales, independientemente de qué tanta infraestructura digital posea el país en términos de administración. Asimismo, estos resultados abrieron otras interrogantes como ¿qué determina el PIB para haber mitigado todo el efecto de administración digital? Sería interesante seguir trabajando en esta línea, con tal de profundizar en la comprensión de los factores a nivel país que influyen en la alfabetización digital de los estudiantes.</p>
<p>Para cerrar, se señalan algunas limitantes del estudio, como el hecho de que se habla educación pero no se consideran las escuelas como un nivel dentro del análisis, por lo que se pierde la posibilidad de capturar otras variables y efectos que serían útiles a considerar. Por otra parte, fue imposible encontrar variables de nivel 2 para todos los países debido a la naturaleza de ellos (como por ejemplo, la Alemania Westfalia-Norte).</p>
</section><section id="anexo" class="level1" data-number="8"><h1 data-number="8">
<span class="header-section-number">8</span> Anexo</h1>
<section id="significancia-de-la-distancia-de-cook" class="level3"><h3 class="anchored" data-anchor-id="significancia-de-la-distancia-de-cook">Significancia de la distancia de Cook</h3>
<div class="cell">
<details class="code-fold"><summary>Código</summary><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">sigtest</span><span class="op">(</span><span class="va">cases</span>, test<span class="op">=</span><span class="op">-</span><span class="fl">1.96</span><span class="op">)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>$Intercept
    Altered.Teststat Altered.Sig Changed.Sig
AUT         4.231736       FALSE       FALSE
AZE         5.156549       FALSE       FALSE
BIH         3.272174       FALSE       FALSE
CHL         4.200612       FALSE       FALSE
CYP         4.190173       FALSE       FALSE
CZE         4.204810       FALSE       FALSE
DEU         4.194473       FALSE       FALSE
DNK         4.005130       FALSE       FALSE
ESP         4.240134       FALSE       FALSE
FIN         4.104059       FALSE       FALSE
FRA         4.225750       FALSE       FALSE
GRC         4.213237       FALSE       FALSE
HRV         4.067122       FALSE       FALSE
HUN         4.068454       FALSE       FALSE
ITA         4.190694       FALSE       FALSE
KAZ         4.090071       FALSE       FALSE
KOR         4.707412       FALSE       FALSE
LUX         4.635771       FALSE       FALSE
LVA         4.098486       FALSE       FALSE
MLT         4.222530       FALSE       FALSE
NLD         4.116181       FALSE       FALSE
NOR         4.218838       FALSE       FALSE
OMN         5.269889       FALSE       FALSE
PRT         4.258271       FALSE       FALSE
ROU         4.212489       FALSE       FALSE
SRB         4.144984       FALSE       FALSE
SVK         4.074435       FALSE       FALSE
SVN         4.214745       FALSE       FALSE
SWE         4.173519       FALSE       FALSE
URY         4.178537       FALSE       FALSE
USA         4.143111       FALSE       FALSE

$sexo.cmc
    Altered.Teststat Altered.Sig Changed.Sig
AUT         32.21384       FALSE       FALSE
AZE         32.58105       FALSE       FALSE
BIH         32.80203       FALSE       FALSE
CHL         32.70053       FALSE       FALSE
CYP         31.94346       FALSE       FALSE
CZE         32.70193       FALSE       FALSE
DEU         32.62394       FALSE       FALSE
DNK         31.71471       FALSE       FALSE
ESP         31.09928       FALSE       FALSE
FIN         32.02916       FALSE       FALSE
FRA         32.48079       FALSE       FALSE
GRC         32.45532       FALSE       FALSE
HRV         31.54017       FALSE       FALSE
HUN         32.52033       FALSE       FALSE
ITA         32.04837       FALSE       FALSE
KAZ         32.85256       FALSE       FALSE
KOR         31.21206       FALSE       FALSE
LUX         32.15443       FALSE       FALSE
LVA         31.93554       FALSE       FALSE
MLT         31.78534       FALSE       FALSE
NLD         32.44537       FALSE       FALSE
NOR         31.76511       FALSE       FALSE
OMN         28.75933       FALSE       FALSE
PRT         32.56574       FALSE       FALSE
ROU         32.52841       FALSE       FALSE
SRB         32.84144       FALSE       FALSE
SVK         32.53179       FALSE       FALSE
SVN         31.56977       FALSE       FALSE
SWE         32.56371       FALSE       FALSE
URY         32.65665       FALSE       FALSE
USA         32.45119       FALSE       FALSE

$iiseb.cmc
    Altered.Teststat Altered.Sig Changed.Sig
AUT         104.9540       FALSE       FALSE
AZE         106.7514       FALSE       FALSE
BIH         106.5456       FALSE       FALSE
CHL         106.3455       FALSE       FALSE
CYP         105.7886       FALSE       FALSE
CZE         102.1889       FALSE       FALSE
DEU         104.2332       FALSE       FALSE
DNK         105.5346       FALSE       FALSE
ESP         102.2034       FALSE       FALSE
FIN         105.4622       FALSE       FALSE
FRA         105.0010       FALSE       FALSE
GRC         105.7203       FALSE       FALSE
HRV         107.0622       FALSE       FALSE
HUN         103.8258       FALSE       FALSE
ITA         105.9331       FALSE       FALSE
KAZ         106.6578       FALSE       FALSE
KOR         106.8652       FALSE       FALSE
LUX         103.2282       FALSE       FALSE
LVA         106.0815       FALSE       FALSE
MLT         106.2724       FALSE       FALSE
NLD         106.3195       FALSE       FALSE
NOR         105.7844       FALSE       FALSE
OMN         106.7248       FALSE       FALSE
PRT         105.2616       FALSE       FALSE
ROU         104.9310       FALSE       FALSE
SRB         105.6749       FALSE       FALSE
SVK         104.6154       FALSE       FALSE
SVN         105.6455       FALSE       FALSE
SWE         105.5386       FALSE       FALSE
URY         105.5316       FALSE       FALSE
USA         105.9473       FALSE       FALSE

$expcompu.cmc
    Altered.Teststat Altered.Sig Changed.Sig
AUT         52.04034       FALSE       FALSE
AZE         51.07102       FALSE       FALSE
BIH         52.33819       FALSE       FALSE
CHL         51.64842       FALSE       FALSE
CYP         51.97414       FALSE       FALSE
CZE         51.06682       FALSE       FALSE
DEU         52.34364       FALSE       FALSE
DNK         52.10236       FALSE       FALSE
ESP         50.46823       FALSE       FALSE
FIN         51.50577       FALSE       FALSE
FRA         52.67793       FALSE       FALSE
GRC         51.61012       FALSE       FALSE
HRV         52.07889       FALSE       FALSE
HUN         52.15815       FALSE       FALSE
ITA         51.51615       FALSE       FALSE
KAZ         50.27422       FALSE       FALSE
KOR         51.72030       FALSE       FALSE
LUX         51.75541       FALSE       FALSE
LVA         52.07288       FALSE       FALSE
MLT         52.10464       FALSE       FALSE
NLD         52.68012       FALSE       FALSE
NOR         52.15685       FALSE       FALSE
OMN         50.93032       FALSE       FALSE
PRT         51.44716       FALSE       FALSE
ROU         51.46438       FALSE       FALSE
SRB         51.82593       FALSE       FALSE
SVK         51.64439       FALSE       FALSE
SVN         52.81885       FALSE       FALSE
SWE         52.06758       FALSE       FALSE
URY         51.54758       FALSE       FALSE
USA         52.05041       FALSE       FALSE

$autoeffgen.cmc
    Altered.Teststat Altered.Sig Changed.Sig
AUT         13.45862       FALSE       FALSE
AZE         12.52682       FALSE       FALSE
BIH         12.59225       FALSE       FALSE
CHL         13.03329       FALSE       FALSE
CYP         12.57824       FALSE       FALSE
CZE         11.59669       FALSE       FALSE
DEU         12.69788       FALSE       FALSE
DNK         12.23553       FALSE       FALSE
ESP         11.71404       FALSE       FALSE
FIN         12.40318       FALSE       FALSE
FRA         12.58198       FALSE       FALSE
GRC         12.51452       FALSE       FALSE
HRV         12.42157       FALSE       FALSE
HUN         11.85908       FALSE       FALSE
ITA         12.70858       FALSE       FALSE
KAZ         12.24225       FALSE       FALSE
KOR         13.03313       FALSE       FALSE
LUX         13.90321       FALSE       FALSE
LVA         12.44424       FALSE       FALSE
MLT         13.19039       FALSE       FALSE
NLD         12.46198       FALSE       FALSE
NOR         10.84918       FALSE       FALSE
OMN         13.27568       FALSE       FALSE
PRT         12.77434       FALSE       FALSE
ROU         12.90495       FALSE       FALSE
SRB         12.50128       FALSE       FALSE
SVK         12.33607       FALSE       FALSE
SVN         13.06794       FALSE       FALSE
SWE         12.78345       FALSE       FALSE
URY         13.30772       FALSE       FALSE
USA         12.89930       FALSE       FALSE

$aprendizaje_escuela.cmc
    Altered.Teststat Altered.Sig Changed.Sig
AUT         2.506765       FALSE       FALSE
AZE         3.743300       FALSE       FALSE
BIH         2.989944       FALSE       FALSE
CHL         2.278258       FALSE       FALSE
CYP         1.634462       FALSE       FALSE
CZE         2.374717       FALSE       FALSE
DEU         2.526117       FALSE       FALSE
DNK         2.519966       FALSE       FALSE
ESP         1.635512       FALSE       FALSE
FIN         2.229478       FALSE       FALSE
FRA         2.237946       FALSE       FALSE
GRC         1.513570       FALSE       FALSE
HRV         1.875199       FALSE       FALSE
HUN         3.087220       FALSE       FALSE
ITA         2.035091       FALSE       FALSE
KAZ         2.112480       FALSE       FALSE
KOR         2.909334       FALSE       FALSE
LUX         1.654721       FALSE       FALSE
LVA         1.662864       FALSE       FALSE
MLT         1.347775       FALSE       FALSE
NLD         2.201094       FALSE       FALSE
NOR         2.509054       FALSE       FALSE
OMN         3.218884       FALSE       FALSE
PRT         2.808802       FALSE       FALSE
ROU         2.600924       FALSE       FALSE
SRB         2.127434       FALSE       FALSE
SVK         2.752817       FALSE       FALSE
SVN         2.839743       FALSE       FALSE
SWE         2.046015       FALSE       FALSE
URY         2.254288       FALSE       FALSE
USA         1.613693       FALSE       FALSE

$logpib
    Altered.Teststat Altered.Sig Changed.Sig
AUT         2.468094       FALSE       FALSE
AZE         1.959429       FALSE       FALSE
BIH         2.514240       FALSE       FALSE
CHL         2.352258       FALSE       FALSE
CYP         2.497100       FALSE       FALSE
CZE         2.479241       FALSE       FALSE
DEU         2.404941       FALSE       FALSE
DNK         2.496394       FALSE       FALSE
ESP         2.530083       FALSE       FALSE
FIN         2.501641       FALSE       FALSE
FRA         2.488542       FALSE       FALSE
GRC         2.498984       FALSE       FALSE
HRV         2.511969       FALSE       FALSE
HUN         2.544053       FALSE       FALSE
ITA         2.474911       FALSE       FALSE
KAZ         1.881494       FALSE       FALSE
KOR         3.019309       FALSE       FALSE
LUX         2.966001       FALSE       FALSE
LVA         2.551844       FALSE       FALSE
MLT         2.483347       FALSE       FALSE
NLD         2.547490       FALSE       FALSE
NOR         2.552531       FALSE       FALSE
OMN         2.945681       FALSE       FALSE
PRT         2.569082       FALSE       FALSE
ROU         2.505260       FALSE       FALSE
SRB         2.495222       FALSE       FALSE
SVK         2.481573       FALSE       FALSE
SVN         2.499870       FALSE       FALSE
SWE         2.512706       FALSE       FALSE
URY         2.386996       FALSE       FALSE
USA         2.708217       FALSE       FALSE

$adm_digital
    Altered.Teststat Altered.Sig Changed.Sig
AUT        0.5480615       FALSE       FALSE
AZE        0.6284200       FALSE       FALSE
BIH        0.9226896       FALSE       FALSE
CHL        0.6075296       FALSE       FALSE
CYP        0.6139487       FALSE       FALSE
CZE        0.7050704       FALSE       FALSE
DEU        0.5803974       FALSE       FALSE
DNK        0.5240801       FALSE       FALSE
ESP        0.4966655       FALSE       FALSE
FIN        0.5081050       FALSE       FALSE
FRA        0.5482758       FALSE       FALSE
GRC        0.5449600       FALSE       FALSE
HRV        0.6714991       FALSE       FALSE
HUN        0.7540804       FALSE       FALSE
ITA        0.5478380       FALSE       FALSE
KAZ        0.9381372       FALSE       FALSE
KOR       -0.1846703       FALSE       FALSE
LUX       -0.3626253       FALSE       FALSE
LVA        0.7250524       FALSE       FALSE
MLT        0.5569500       FALSE       FALSE
NLD        0.5989765       FALSE       FALSE
NOR        0.5088494       FALSE       FALSE
OMN        0.2820325       FALSE       FALSE
PRT        0.5626880       FALSE       FALSE
ROU        0.5082978       FALSE       FALSE
SRB        0.5545089       FALSE       FALSE
SVK        0.6752749       FALSE       FALSE
SVN        0.5498011       FALSE       FALSE
SWE        0.4946607       FALSE       FALSE
URY        0.6237019       FALSE       FALSE
USA        0.5943784       FALSE       FALSE</code></pre>
</div>
</div>

</section></section><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">Referencias</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-aesaert_information_2018" class="csl-entry" role="listitem">
Aesaert, Koen, y Johan van Braak. 2018. <span>«Information and <span>Communication Competences</span> for <span>Students</span>»</span>. En <em>Second <span>Handbook</span> of <span>Information Technology</span> in <span>Primary</span> and <span>Secondary Education</span></em>, 1-15. Springer, Cham. <a href="https://doi.org/10.1007/978-3-319-53803-7_22-2">https://doi.org/10.1007/978-3-319-53803-7_22-2</a>.
</div>
<div id="ref-aydin_multilevel_2022" class="csl-entry" role="listitem">
Aydin, Mustafa. 2022. <span>«A Multilevel Modeling Approach to Investigating Factors Impacting Computer and Information Literacy: <span>ICILS Korea</span> and <span>Finland</span> Sample»</span>. <em>Education and Information Technologies</em> 27 (2): 1675-1703. <a href="https://doi.org/10.1007/s10639-021-10690-1">https://doi.org/10.1007/s10639-021-10690-1</a>.
</div>
<div id="ref-bandura_selfefficacy_1982a" class="csl-entry" role="listitem">
Bandura, Albert. 1982. <span>«Self-Efficacy Mechanism in Human Agency»</span>. <em>American Psychologist</em> 37 (2): 122-47. <a href="https://doi.org/10.1037/0003-066X.37.2.122">https://doi.org/10.1037/0003-066X.37.2.122</a>.
</div>
<div id="ref-barroso_investigacion_2011" class="csl-entry" role="listitem">
Barroso, J., y J. Cabero. 2011. <em>La Investigaci<span>ó</span>n Educativa En <span>TIC</span></em>. Madrid: S<span>í</span>ntesis.
</div>
<div id="ref-bourdieu_herederos_2009" class="csl-entry" role="listitem">
Bourdieu, Pierre, y Jean-Claude Passeron. 2009. <em>Los Herederos: Los Estudiantes y La Cultura</em>. Buenos Aires: Siglo Veintiuno Editores.
</div>
<div id="ref-buckingham_mas_2008" class="csl-entry" role="listitem">
Buckingham, David. 2008. <em><span>Mas all<span>á</span> de la tecnolog<span>í</span>a: aprendizaje infantil en la era de la cultura digital</span></em>. 1. ed. <span>Biblioteca del docente</span>. Buenos Aires: Manantial.
</div>
<div id="ref-busemeyer_digitalization_2022" class="csl-entry" role="listitem">
Busemeyer, Edited by Marius R., Achim Kemmerling, Kees Van Kersbergen, y and Paul Marx, eds. 2022. <em>Digitalization and the <span>Welfare State</span></em>. Oxford, New York: Oxford University Press.
</div>
<div id="ref-cabero_tendencias_2016" class="csl-entry" role="listitem">
Cabero, Julio. 2016. <em><span>Tendencias educativas para el siglo XXI</span></em>.
</div>
<div id="ref-camacho_brecha_2005" class="csl-entry" role="listitem">
Camacho, K. 2005. <span>«<span>La Brecha digital</span>»</span>. <em>Palabras en juego: enfoques multiculturales sobre las sociedades de la informaci<span>ó</span>n</em>, 61-71.
</div>
<div id="ref-caponera_exploring_2025" class="csl-entry" role="listitem">
Caponera, Elisa, Francesco Annunziata, y Laura Palmerio. 2025. <span>«Exploring <span>Gender Differences</span> in <span>ICT Skills</span>: <span>Insights</span> from <span>Italian Results</span> in <span>ICILS</span> 2023»</span>.
</div>
<div id="ref-castells_sociedad_2006" class="csl-entry" role="listitem">
Castells, M. 2006. <em>La Sociedad Red: Una Visi<span>ó</span>n Global</em>. Madrid: Alianza Editorial.
</div>
<div id="ref-cervini_desigualdades_2002" class="csl-entry" role="listitem">
Cervini, Rubén. 2002. <span>«<span>Desigualdades en el logro acad<span>é</span>mico y reproducci<span>ó</span>n cultural en Argentina. Un modelo de tres niveles</span>»</span>. <em>Revista Mexicana de Investigaci<span>ó</span>n Educativa</em> 7 (16): 445-500.
</div>
<div id="ref-chaparrocasolopez_familia_2016" class="csl-entry" role="listitem">
Chaparro Caso López, Alicia Alelí, Coral González Barbera, y Joaquín Caso Niebla. 2016. <span>«<span>Familia y rendimiento acad<span>é</span>mico: configuraci<span>ó</span>n de perfiles estudiantiles en secundaria</span>»</span>. <em>Revista electr<span>ó</span>nica de investigaci<span>ó</span>n educativa</em> 18 (1): 53-68.
</div>
<div id="ref-claro_impacto_2010" class="csl-entry" role="listitem">
Claro, Magdalena. 2010. <span>«<span>Impacto de las TIC en los aprendizajes de los estudiantes: estado del arte</span>»</span>. CEPAL.
</div>
<div id="ref-collins_sociedad_1989" class="csl-entry" role="listitem">
Collins, Randall. 1989. <em>La Sociedad Credencialista</em>. Ediciones Akal.
</div>
<div id="ref-dijk_digital_2020" class="csl-entry" role="listitem">
Dijk, Jan van. 2020. <em>The Digital Divide</em>. Cambridge Medford: Polity.
</div>
<div id="ref-fairlie_boys_2016" class="csl-entry" role="listitem">
Fairlie, Robert W. 2016. <span>«Do <span>Boys</span> and <span>Girls Use Computers Differently</span>, and <span>Does It Contribute</span> to <span>Why Boys</span> Do <span>Worse</span> in <span>School Than Girls</span>?»</span> <em>The B.E. Journal of Economic Analysis &amp; Policy</em> 16 (1): 59-96. <a href="https://doi.org/10.1515/bejeap-2015-0094">https://doi.org/10.1515/bejeap-2015-0094</a>.
</div>
<div id="ref-fraillon_icils_2024" class="csl-entry" role="listitem">
Fraillon, Julian. 2024. <span>«<span>ICILS</span> 2023 <span>International Report</span>: <span>An International Perspective</span> on <span>Digital Literacy</span> <span></span> <span>IEA</span>.Nl»</span>. https://www.iea.nl/publications/icils-2023-international-report.
</div>
<div id="ref-fraillon_preparing_2020" class="csl-entry" role="listitem">
Fraillon, Julian, John Ainley, Wolfram Schulz, Tim Friedman, y Daniel Duckworth. 2020. <em>Preparing for <span>Life</span> in a <span>Digital World</span>: <span>IEA International Computer</span> and <span>Information Literacy Study</span> 2018 <span>International Report</span></em>. Cham: Springer International Publishing. <a href="https://doi.org/10.1007/978-3-030-38781-5">https://doi.org/10.1007/978-3-030-38781-5</a>.
</div>
<div id="ref-fraillon_icils_2013" class="csl-entry" role="listitem">
Fraillon, Julian, Wolfram Schulz, Tim Friedman, John Ainley, y Eveline Gebhardt. 2013. <em><span>ICILS</span> 2013: Technical Report</em>. Amsterdam Netherlands: IEA Secretariat.
</div>
<div id="ref-garcia-avila_alfabetizacion_2017" class="csl-entry" role="listitem">
García-Ávila, Susana. 2017. <span>«<span>Alfabetizaci<span>ó</span>n Digital</span>»</span>. <em>Raz<span>ó</span>n y Palabra</em> 21 (3_98): 66-81.
</div>
<div id="ref-gerick_schoollevel_2017" class="csl-entry" role="listitem">
Gerick, Julia, Birgit Eickelmann, y Wilfried Bos. 2017. <span>«School-Level Predictors for the Use of <span>ICT</span> in Schools and Students’ <span>CIL</span> in International Comparison»</span>. <em>Large-scale Assessments in Education</em> 5 (1): 5. <a href="https://doi.org/10.1186/s40536-017-0037-7">https://doi.org/10.1186/s40536-017-0037-7</a>.
</div>
<div id="ref-hatlevik_digital_2015" class="csl-entry" role="listitem">
Hatlevik, Ove Edvard, Gréta Björk Gumundsdóttir, y Massimo Loi. 2015. <span>«Digital Diversity among Upper Secondary Students: <span>A</span> Multilevel Analysis of the Relationship between Cultural Capital, Self-Efficacy, Strategic Use of Information and Digital Competence»</span>. <em>Computers &amp; Education</em> 81 (febrero): 345-53. <a href="https://doi.org/10.1016/j.compedu.2014.10.019">https://doi.org/10.1016/j.compedu.2014.10.019</a>.
</div>
<div id="ref-heldt_relationship_2020" class="csl-entry" role="listitem">
Heldt, Melanie, Corinna Massek, Kerstin Drossel, y Birgit Eickelmann. 2020. <span>«The Relationship Between Differences in Students’ Computer and Information Literacy and Response Times: An Analysis of <span>IEA-ICILS</span> Data»</span>. <em>Large-Scale Assessments in Education</em> 8 (1): 12. <a href="https://doi.org/10.1186/s40536-020-00090-1">https://doi.org/10.1186/s40536-020-00090-1</a>.
</div>
<div id="ref-hox_multilevel_2017" class="csl-entry" role="listitem">
Hox, Joop J. 2017. <span>«Multilevel <span>Analysis</span>: <span>Techniques</span> and <span>Applications</span>»</span>.
</div>
<div id="ref-iea_pirls_2021" class="csl-entry" role="listitem">
IEA. 2021. <span>«<span>PIRLS</span> 2021 <span>International Results</span> in <span>Reading</span> – <span>About PIRLS</span> 2021 – <span>PIRLS</span> 2021»</span>.
</div>
<div id="ref-nand_metaheuristic_2019" class="csl-entry" role="listitem">
Nand, Ravneil, y Anuraganand Sharma. 2019. <span>«Meta-Heuristic Approaches to Tackle <span>Skill Based Group</span> Allocation of <span>Students</span> in <span>Project Based Learning Courses</span>»</span>. En <em>2019 <span>IEEE Congress</span> on <span>Evolutionary Computation</span> (<span>CEC</span>)</em>, 1782-89. <a href="https://doi.org/10.1109/CEC.2019.8789987">https://doi.org/10.1109/CEC.2019.8789987</a>.
</div>
<div id="ref-oecd_pisa_2023" class="csl-entry" role="listitem">
OECD. 2023. <span>«<span>PISA 2022 Results (Volume I)</span>»</span>. <em>OECD</em>. https://www.oecd.org/en/publications/pisa-2022-results-volume-i_53f23881-en.html.
</div>
<div id="ref-pojani_sustainable_2015" class="csl-entry" role="listitem">
Pojani, Dorina, y Dominic Stead. 2015. <span>«Sustainable <span>Urban Transport</span> in the <span>Developing World</span>: <span>Beyond Megacities</span>»</span>. <em>Sustainability</em> 7 (6): 7784-7805. <a href="https://doi.org/10.3390/su7067784">https://doi.org/10.3390/su7067784</a>.
</div>
<div id="ref-punter_gender_2017" class="csl-entry" role="listitem">
Punter, R Annemiek, Martina RM Meelissen, y Cees AW Glas. 2017. <span>«Gender Differences in Computer and Information Literacy: <span>An</span> Exploration of the Performances of Girls and Boys in <span>ICILS</span> 2013»</span>. <em>European Educational Research Journal</em> 16 (6): 762-80. <a href="https://doi.org/10.1177/1474904116672468">https://doi.org/10.1177/1474904116672468</a>.
</div>
<div id="ref-reddy_student_2020" class="csl-entry" role="listitem">
Reddy, Pritika, Bibhya Sharma, y Shaneel Chandra. 2020. <span>«Student <span>Readiness</span> and <span>Perception</span> of <span>Tablet Learning</span> in <span>Higher Education</span> in the <span>Pacific- A Case Study</span> of <span>Fiji</span> and <span>Tuvalu</span>: <span>Tablet Learning</span> at <span>USP</span>»</span>. <em>Journal of Cases on Information Technology (JCIT)</em> 22 (2): 52-69. <a href="https://doi.org/10.4018/JCIT.2020040104">https://doi.org/10.4018/JCIT.2020040104</a>.
</div>
<div id="ref-reddy_tablet_2017" class="csl-entry" role="listitem">
Reddy, P., B. Sharma, y S. Chandra. 2017. <span>«Tablet Learning and Its Perceived Usage at a Higher Education Institute in <span>Fiji</span>»</span>. <em>Fijian Studies: A Journal of Contemporary Fiji</em>, 131-42.
</div>
<div id="ref-scherer_gender_2023" class="csl-entry" role="listitem">
Scherer, Ronny, Fazilat Siddiq, Sarah K. Howard, y Jo Tondeur. 2023. <span>«Gender Divides in Teachers’ Readiness for Online Teaching and Learning in Higher Education: <span>Do</span> Women and Men Consider Themselves Equally Prepared?»</span> <em>Computers &amp; Education</em> 199 (julio): 104774. <a href="https://doi.org/10.1016/j.compedu.2023.104774">https://doi.org/10.1016/j.compedu.2023.104774</a>.
</div>
<div id="ref-sharma_smart_2018" class="csl-entry" role="listitem">
Sharma, Bibhya Nand, Ravneil Nand, Mohammed Naseem, Emmenual Reddy, Swasti Shubha Narayan, y Karuna Reddy. 2018. <span>«Smart <span>Learning</span> in the <span>Pacific</span>: <span>Design</span> of <span>New Pedagogical Tools</span>»</span>. En <em>2018 <span>IEEE International Conference</span> on <span>Teaching</span>, <span>Assessment</span>, and <span>Learning</span> for <span>Engineering</span> (<span>TALE</span>)</em>, 573-80. <a href="https://doi.org/10.1109/TALE.2018.8615269">https://doi.org/10.1109/TALE.2018.8615269</a>.
</div>
<div id="ref-sharma_use_2015" class="csl-entry" role="listitem">
Sharma, Bibhya N., Anjeela D. Jokhan, Raneel Kumar, Rona W. Finiasi, Sanjeet Chand, y Varunesh Rao. 2015. <span>«Use of Short Message Service for Learning and Student Support in the <span>Pacific</span> Region»</span>. En, editado por Y. Zhang, 199-220. Berlin: Springer.
</div>
<div id="ref-silvera_alfabetizacion_2005" class="csl-entry" role="listitem">
Silvera, Claudia. 2005. <span>«La Alfabetizaci<span>ó</span>n Digital: Una Herramienta Para Alcanzar El Desarrollo y La Equidad En Los Pa<span>í</span>ses de <span>Am<span>é</span>rica</span> Latina y El <span>Caribe</span>»</span>. <em>ACIMED</em> 13 (1): 1-8.
</div>
<div id="ref-sunkel_aprender_2011" class="csl-entry" role="listitem">
Sunkel, Guillermo, Daniela Trucco, y Sebastián Möller. 2011. <em>Aprender y Ense<span>ñ</span>ar Con Las Tecnolog<span>í</span>as de La Informaci<span>ó</span>n y Las Comunicaciones En <span>Am<span>é</span>rica Latina</span>: Potenciales Beneficios</em>. CEPAL.
</div>
<div id="ref-tsai_junior_2010" class="csl-entry" role="listitem">
Tsai, Meng-Jung, y Chin-Chung Tsai. 2010. <span>«Junior High School Students’ <span>Internet</span> Usage and Self-Efficacy: <span>A</span> Re-Examination of the Gender Gap»</span>. <em>Computers &amp; Education</em> 54 (4): 1182-92. <a href="https://doi.org/10.1016/j.compedu.2009.11.004">https://doi.org/10.1016/j.compedu.2009.11.004</a>.
</div>
</div></section></div></main><!-- /main column --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>